name: Build SouthWest-NG Kernel

on:
  workflow_dispatch:
    inputs:
      include_ksu:
        description: 'Build with ReSukiSU (KernelSU)?'
        required: true
        type: boolean
        default: true
      include_susfs:
        description: 'Build with SUSFS (Requires ReSukiSU/KernelSU)?'
        required: true
        type: boolean
        default: false

jobs:
  build:
    name: Build Kernel (${{ (inputs.include_susfs == true || inputs.include_ksu == true) && (inputs.include_susfs == true && 'KSU+SUSFS' || 'KSU') || 'Vanilla' }})
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: Run build script
        run: |
          chmod +x build.sh
          BUILD_FLAGS=""
          if [ "${{ inputs.include_ksu }}" == "true" ]; then
            BUILD_FLAGS="$BUILD_FLAGS --ksu"
            if [ "${{ inputs.include_susfs }}" == "true" ]; then
              BUILD_FLAGS="$BUILD_FLAGS --susfs"
            fi
          elif [ "${{ inputs.include_susfs }}" == "true" ]; then
            BUILD_FLAGS="--ksu --susfs"
          fi
          ./build.sh $BUILD_FLAGS

      - name: Upload Kernel Zip
        uses: actions/upload-artifact@v4
        with:
          name: SouthWest-NG-lavender-${{ (inputs.include_susfs == true || inputs.include_ksu == true) && (inputs.include_susfs == true && 'KSU-SUSFS' || 'KSU') || 'NoKSU' }}
          path: "*.zip"
